---
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Demo

Parameters:
  ArtifactBucket:
    Type: String

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Configuration
        Parameters:
          - ArtifactBucket
    ParameterLabels:
      ArtifactBucket:
        default: Artifact Bucket

Resources:
  Queue:
    Type: AWS::SQS::Queue

  Func:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/func
      Handler: index.handler
      Runtime: python2.7
      Policies:
        - Version: 2012-10-17
          Statement:
            - Sid: SQSAccess
              Effect: Allow
              Action: sqs:SendMessage
              Resource: !GetAtt Queue.Arn
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)

  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: !Sub s3://${ArtifactBucket}/template.yml
  CustomDeadLetterQueue:
    Type: Custom::DeadLetterQueue
    Version: 1.0
    Properties:
      ServiceToken: !GetAtt LambdaDeadLetterQueue.Arn
      FunctionName: !Ref Func
      TargetArn: !GetAtt Queue.Arn

Outputs:
  FuncName:
    Value: !Ref Func
